language: python
python:
 - "2.7"

install: "pip install -r requirements.txt"

before_script:
 - autopep8 -ir *
 - flake8 --max-complexity=3 --exclude=*.txt,*.md --max-line-length=200 *

script:
 - lettuce test
 - python TestCalculator.py -v
 - coverage run --branch TestCalculator.py
 - coverage report -m
